# Generated by Django 3.1.2 on 2020-10-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public',
            old_name='district',
            new_name='district1',
        ),
        migrations.RenameField(
            model_name='public',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='public',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='public',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='public',
            old_name='username',
            new_name='username1',
        ),
    ]
