# Generated by Django 3.1.2 on 2020-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_gathering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date4',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='mobile4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time4',
            field=models.TimeField(),
        ),
    ]
