# Generated by Django 3.1.2 on 2020-10-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20201007_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address4',
            field=models.CharField(max_length=320),
        ),
    ]
