# Generated by Django 3.1.2 on 2020-10-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20201009_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='cause5',
            field=models.CharField(max_length=420),
        ),
        migrations.AlterField(
            model_name='gathering',
            name='place5',
            field=models.CharField(max_length=80),
        ),
    ]
