# Generated by Django 3.1.2 on 2020-10-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20201009_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address4',
            field=models.CharField(max_length=420),
        ),
        migrations.AlterField(
            model_name='event',
            name='date4',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='mobile4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='time4',
            field=models.TimeField(max_length=30),
        ),
    ]
