# Generated by Django 3.1.2 on 2020-10-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20201009_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='cause5',
            field=models.CharField(max_length=820),
        ),
    ]
