# Generated by Django 3.1.2 on 2020-10-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20201009_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.CharField(max_length=230),
        ),
    ]
